### ISSUE TITLE
Create Front end template

### ISSUE THREAD

**Issue by Raashul** [Raashul/Insta-clone#1]
Create a template for each page in the web app. 
Login - Signup, Signin
Home Page
Profile
Each Photo
Notification

**Comment by Sauasmast** [comment]
I have attached a front end template on this issue please check it out. I have created the home page, search button , login and sign up and as well as the profile thing but the profile thing is not yet finished. It will be finished as time passes by. You will be able to find the template on my branch too. I would request a pull to the main branch check it out and let me know.  The file is too big so i will not be able to attach it in the comment. So please checkout my branch.
